# Generated by Django 3.2.4 on 2021-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorday',
            name='status',
            field=models.CharField(choices=[('free', 'free'), ('reserved', 'reserved')], default='free', max_length=10),
        ),
    ]
