# Generated by Django 3.2.4 on 2021-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_doctorday_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
